env: "local"

database:
  host: "localhost"
  port: 5432
  user: "messagio"
  password: "1234"
  dbname: "messagio-tk"

kafka:
  brokers:
    - "localhost:9092"
  topics:
    message_group: ["handle"]

grpc:
  host: "localhost"
  port: 50051
  timeout: 5  # in seconds

http_port: 8082

