env: "local"

database:
  host: "localhost"
  port: 5432
  user: "messagio"
  password: "1234"
  dbname: "messagio-tk"

kafka:
  brokers:
    - "broker1:9092"
    - "broker2:9092"

grpc:
  host: "localhost"
  port: 50051
  timeout: 5  # in seconds

http_port: 8082

